use_frameworks!
platform :ios, '10.0'

target 'app-version-swift_Example' do
  pod 'app-version-swift', :path => '../'

  target 'app-version-swift_Tests' do
    inherit! :search_paths

    
  end
end
